### ISSUE TITLE
Linking CPLEX to the conda environment

### ISSUE THREAD

**Issue by NoodleChad** [klamt-lab/straindesign#13]
upon running 'python setup.py install' in the directory of CPLEX, I get a message saying install is no longer supported.
I fixed by downgrading setuptools to setuptools==58.2.0

**Comment by VonAlphaBisZulu** [comment]
I was able to reproduce your problem. Finally, I managed to install it with pip through something like `pip install C:\Program Files\IBM\ILOG\CPLEX_Studio201\cplex\python\3.8\x64_win64`.

Thank you for posting the issue. I will try to get this to work reliably and update the documentation and also put setuptools there. I don't know why IBM still recommends 'python setup.py install'
